export const ADD_BASKET_LIST = "ADD_BASKET_LIST"
export const REMOVE_BASKET_LIST = "REMOVE_BASKET_LIST"
export const CLEAR_BASKET_LIST = "CLEAR_BASKET_LIST"
export const PLUS_AMOUNT ="PLUS_AMOUNT"
export const MINUS_AMOUNT ="MINUS_AMOUNT"


export const ADD_FAVORITE_LIST = "ADD_FAVORITE_LIST"
export const REMOVE_FAVORITE_LIST = "REMOVE_FAVORITE_LIST"
export const CLEAR_FAVORITE_LIST = "CLEAR_FAVORITE_LIST"
